# Generated by Django 5.0.4 on 2024-05-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_author_rating_alter_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('AR', 'Статья'), ('NE', 'Новость')], default='AR', max_length=8),
        ),
    ]
